# SPDX-FileCopyrightText: : 2017-2024 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#top-level-configuration
version: 0.13.0
tutorial: false

logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'

remote:
  ssh: ""
  path: ""

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  prefix: "initial_main_scenarios"
  name: "all"
  scenarios:
    enable: true
    file: config/scenarios.form.yaml
  disable_progressbar: false
  shared_resources:
    policy: false
    exclude: []
  shared_cutouts: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: myopic

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#scenario
# Wildcard docs in https://pypsa-eur.readthedocs.io/en/latest/wildcards.html
scenario:
  ll:
  - v1.11  # v1.x with x according to additional NEP links (existing_capacities=zero)
  clusters:
  - 52
  planning_horizons:
  - 2035

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#countries
countries: ['AT', 'BE', 'CH', 'CZ', 'DE', 'DK', 'FR', 'IT', 'LU', 'NL', 'PL', 'SE']

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#snapshots
snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: 'left'

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: auto
  retrieve_databundle: true
  retrieve_cost_data: true
  build_cutout: false
  retrieve_cutout: false
  custom_busmap: false
  drop_leap_day: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#co2-budget
co2_budget:
  2035: 0.195 # derived from individual countries carbon emission targets for included sectors

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#electricity
electricity:
  max_hours:
    li-ion battery: [1, 2, 4, 8]
    vanadium: [10]
    lair: [12]
    pair: [24]
    H2: [168]
    iron-air battery: [100]
  extendable_carriers:
    Generator: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float]
  powerplants_filter: DateOut >= 2024 and not Fueltype.isin(['Nuclear', 'Hard Coal', 'Lignite'])
  custom_powerplants: DateIn <= 2024 and DateOut >= 2024

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#atlite
atlite:
  # TODO: weather year - input from FORM
  default_cutout: europe-2013-sarah3-era5
  nprocesses: 4
  show_progress: false
  cutouts:
    # use 'base' to determine geographical bounds and time span from config
    # base:
      # module: era5
    europe-2013-sarah3-era5:
      module: [sarah, era5] # in priority order
      x: [-12., 42.]
      y: [33., 72.]
      dx: 0.3
      dy: 0.3
      time: ['2013', '2013']

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#renewable
renewable:
  hydro:
    PHS_max_hours: 10

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#lines
lines:
  s_max_pu: 0.5
  dynamic_line_rating:
    activate: false
    cutout: europe-2013-sarah3-era5
    correction_factor: 0.95
    max_voltage_difference: 30 # Glaum & Hofmann, 2022 https://arxiv.org/abs/2208.04716
    max_line_rating: 1.5 # based on https://www.energysystem2050.net/content/TransnetBW-Study_EnergySystem2050.pdf?v2, p.81

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#transmission_projects
transmission_projects:
  enable: true
  include:
    tyndp2020: false
    nep: true
    manual: false
  skip:
  - upgraded_lines
  - upgraded_links
  status:
  - under_construction
  - in_permitting
  - confirmed
    #- planned_not_yet_permitted
    #- under_consideration
  new_link_capacity: zero #keep or zero

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#existing-capacities
# TODO: add option for manual phase out of conventional power plants
existing_capacities:
  grouping_years_power: [1920, 1950, 1955, 1960, 1965, 1970, 1975, 1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020, 2025]
  grouping_years_heat: [1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2019] # heat grouping years >= baseyear will be ignored
  threshold_capacity: 10
  default_heating_lifetime: 20
  conventional_carriers:
  - lignite
  - coal
  - oil
  - uranium

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#sector
sector:
  transport: true
  heating: true
  biomass: false
  industry: false
  agriculture: false
  fossil_fuels: true
  bev_dsm: true
  bev_dsm_availability: 0.2 # FE input
  v2g: true
  land_transport_fuel_cell_share:
    2035: 0
  land_transport_electric_share:
    2035: 0.30 # FE input
  land_transport_ice_share:
    2035: 0.70
  reduce_space_heat_exogenously: true
  reduce_space_heat_exogenously_factor: # TODO: check this for Germany (Regulation or Ariadne?)
    2035: 0.11
  tes: false
  marginal_cost_storage: 0. #1e-4
  stores: ["H2"]
  storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
  hydrogen_fuel_cell: true
  hydrogen_turbine: false
  hydrogen_underground_storage: true
  hydrogen_underground_storage_locations:
    # - onshore  # more than 50 km from sea
  - nearshore    # within 50 km of sea
    # - offshore
  H2_network: false
  gas_network: false
  H2_retrofit: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#costs
costs:
  year: 2035
  version: 67a5830
  social_discountrate: 0.02
  fill_values:
    FOM: 0
    VOM: 0
    efficiency: 1
    fuel: 0
    investment: 0
    lifetime: 25
    "CO2 intensity": 0
    "discount rate": 0.07
  # Marginal and capital costs can be overwritten
  # capital_cost:
  #   onwind: 500
  fuel:
    OCGT: 38.84 # https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:52022SC0230 (Annex)
    CCGT: 38.84
    gas: 38.84
    coal: 24.57 # https://businessanalytiq.com/procurementanalytics/index/subbituminous-coal-price-index/
    lignite: 22.11 # https://businessanalytiq.com/procurementanalytics/index/lignite-coal-price-index/
    nuclear: 1.75 # https://markets.businessinsider.com/commodities/uranium-price
    uranium: 1.75
  efficiency:
    Compressed-Air-Adiabatic-bicharger: 0.7745
  investment:
    iron-air battery: 23500  # in EUR/MWh
  marginal_cost:
    solar: 0.01
    onwind: 0.015
    offwind: 0.015
    hydro: 0.
    H2: 0.
    electrolysis: 0.
    fuel cell: 0.
    li-ion battery: 0.
    battery inverter: 0.
  emission_prices:
    enable: false
    co2: 0.
    co2_monthly_prices: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#clustering
clustering:
  focus_weights:
    DE: 0.6
  temporal:
    resolution_sector: 1H #2920SEG

plotting:
  tech_colors:
    # all battery variation:
    lfp: '#ace37f'
    vanadium: '#9B111E'
    lair: '#87CEEB'
    pair: '#003366'
    iron-air battery: '#edba1c'
    Iron-Air battery storage: '#edba1c'
    Li-Ion battery storage: '#ace37f'
    other battery storage: '#80c944'

solving:
  mem_mb: 150000 #memory in MB; 20 GB enough for 50+B+I+H2; 100 GB for 181+B+I+H2
  runtime: 24h #runtime in humanfriendly style https://humanfriendly.readthedocs.io/en/latest/