# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

main-no-mds:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: []
    storage_units: ["li-ion battery", "vanadium", "lair", "pair"]

main-mds:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]

main-mds-h2-storage:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: []
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery", "H2"]

main-mds-no-methanation:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
    methanation: false

main-mds-vanilla:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "iron-air battery"]

main-no-mds-vanilla:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: []
    storage_units: ["li-ion battery"]

main-mds-vanilla-no-methanation:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "iron-air battery"]
    methanation: false

main-mds-vanilla-with-grids:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "iron-air battery"]
    H2_network: true
    gas_network: true
    H2_retrofit: true

main-calibration-run:
  enable:
    final_adjustment: false
  scenario:
    ll:
    - v1.0
    planning_horizons:
    - 2023
  snapshots:
    start: "2023-01-01"
    end: "2024-01-01"
  co2_budget:
    2023: 0.378 
    # 63% from https://commission.europa.eu/news/climate-report-shows-largest-annual-drop-eu-greenhouse-gas-emissions-decades-2024-11-05_en
    # 60% factored in emission included sector from co2_totals_sector.csv (interpolation between 2015, 2030)
    # 0.63 * 0.6 = 0.378
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
    powerplants_filter: DateOut >= 2023 and not Fueltype.isin(['Nuclear', 'Hard Coal', 'Lignite'])
    custom_powerplants: DateIn <= 2023 and DateOut >= 2023
  atlite:
    default_cutout: europe-2023-sarah3-era5
  renewable:
    onwind:
      cutout: europe-2023-sarah3-era5
    offwind-ac:
      cutout: europe-2023-sarah3-era5
    offwind-dc:
      cutout: europe-2023-sarah3-era5
    offwind-float:
      cutout: europe-2023-sarah3-era5
    solar:
      cutout: europe-2023-sarah3-era5
    solar-hsat:
      cutout: europe-2023-sarah3-era5
    hydro:
      cutout: europe-2023-sarah3-era5
  biomass:
    year: 2020
  sector:
    district_heating:
      progress:
        2023: 0.15 #Rough estimate. 70M/448M population uses district heating https://iifiir.org/en/news/state-of-play-of-district-heating-and-cooling-in-europe
    land_transport_fuel_cell_share:
      2023: 0
    land_transport_electric_share:
      2023: 0.02 #https://ec.europa.eu/eurostat/web/products-eurostat-news/w/ddn-20240802-1
    land_transport_ice_share:
      2023: 0.98 # 1.00 - 0.02
    co2_sequestration_potential:
      2023: 0
    stores: []
    storage_units: ["li-ion battery"]
    methanation: false
  costs:
    year: 2020
