# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

main-no-mds:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: []
    storage_units: ["li-ion battery", "vanadium", "lair", "pair"]

main-mds:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]

main-mds-h2-storage:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: []
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery", "H2"]

main-mds-no-methanation:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
    methanation: false

main-mds-vanilla:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "iron-air battery"]

main-no-mds-vanilla:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: []
    storage_units: ["li-ion battery"]

main-mds-vanilla-no-methanation:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "iron-air battery"]
    methanation: false

main-mds-vanilla-with-grids:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "iron-air battery"]
    H2_network: true
    gas_network: true
    H2_retrofit: true

main-calibration-run:
  snapshots:
    start: "2023-01-01"
    end: "2024-01-01"
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
