# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

baseline-mds:
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]

baseline-nomds:
  sector:
    stores: []
    storage_units: ["li-ion battery", "vanadium", "lair", "pair"]

mid-capex-mds:
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
  costs:
    investment:
      iron-air battery: 18477  # in EUR/MWh (2020) from 20,000 EUR/MWh (2024)

low-capex-mds:
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
  costs:
    investment:
      iron-air battery: 14089  # in EUR/MWh (2020) from 15,250 EUR/MWh (2024)

cy2010-mds:
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
  snapshots:
    start: "2010-01-01"
    end: "2011-01-01"
  atlite:
    default_cutout: europe-2010-sarah3-era5
    cutouts:
      europe-2010-sarah3-era5:
        module: [sarah, era5] # in priority order
        x: [-12., 42.]
        y: [33., 72.]
        dx: 0.3
        dy: 0.3
        time: ['2010', '2010']
  renewable:
    onwind:
      cutout: europe-2010-sarah3-era5
    offwind-ac:
      cutout: europe-2010-sarah3-era5
    offwind-dc:
      cutout: europe-2010-sarah3-era5
    offwind-float:
      cutout: europe-2010-sarah3-era5
    solar:
      cutout: europe-2010-sarah3-era5
    solar-hsat:
      cutout: europe-2010-sarah3-era5
    hydro:
      cutout: europe-2010-sarah3-era5

cy2010-nomds:
  sector:
    stores: []
    storage_units: ["li-ion battery", "vanadium", "lair", "pair"]
  snapshots:
    start: "2010-01-01"
    end: "2011-01-01"
  atlite:
    default_cutout: europe-2010-sarah3-era5
    cutouts:
      europe-2010-sarah3-era5:
        module: [sarah, era5] # in priority order
        x: [-12., 42.]
        y: [33., 72.]
        dx: 0.3
        dy: 0.3
        time: ['2010', '2010']
  renewable:
    onwind:
      cutout: europe-2010-sarah3-era5
    offwind-ac:
      cutout: europe-2010-sarah3-era5
    offwind-dc:
      cutout: europe-2010-sarah3-era5
    offwind-float:
      cutout: europe-2010-sarah3-era5
    solar:
      cutout: europe-2010-sarah3-era5
    solar-hsat:
      cutout: europe-2010-sarah3-era5
    hydro:
      cutout: europe-2010-sarah3-era5

cy2012-mds:
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
  snapshots:
    start: "2012-01-01"
    end: "2013-01-01"
  atlite:
    default_cutout: europe-2012-sarah3-era5
    cutouts:
      europe-2012-sarah3-era5:
        module: [sarah, era5] # in priority order
        x: [-12., 42.]
        y: [33., 72.]
        dx: 0.3
        dy: 0.3
        time: ['2012', '2012']
  renewable:
    onwind:
      cutout: europe-2012-sarah3-era5
    offwind-ac:
      cutout: europe-2012-sarah3-era5
    offwind-dc:
      cutout: europe-2012-sarah3-era5
    offwind-float:
      cutout: europe-2012-sarah3-era5
    solar:
      cutout: europe-2012-sarah3-era5
    solar-hsat:
      cutout: europe-2012-sarah3-era5
    hydro:
      cutout: europe-2012-sarah3-era5

cy2012-nomds:
  sector:
    stores: []
    storage_units: ["li-ion battery", "vanadium", "lair", "pair"]
  snapshots:
    start: "2012-01-01"
    end: "2013-01-01"
  atlite:
    default_cutout: europe-2012-sarah3-era5
    cutouts:
      europe-2012-sarah3-era5:
        module: [sarah, era5] # in priority order
        x: [-12., 42.]
        y: [33., 72.]
        dx: 0.3
        dy: 0.3
        time: ['2012', '2012']
  renewable:
    onwind:
      cutout: europe-2012-sarah3-era5
    offwind-ac:
      cutout: europe-2012-sarah3-era5
    offwind-dc:
      cutout: europe-2012-sarah3-era5
    offwind-float:
      cutout: europe-2012-sarah3-era5
    solar:
      cutout: europe-2012-sarah3-era5
    solar-hsat:
      cutout: europe-2012-sarah3-era5
    hydro:
      cutout: europe-2012-sarah3-era5

cy1996-mds:
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
  snapshots:
    start: "1996-01-01"
    end: "1997-01-01"
  atlite:
    default_cutout: europe-1996-sarah3-era5
    cutouts:
      europe-1996-sarah3-era5:
        module: [sarah, era5] # in priority order
        x: [-12., 42.]
        y: [33., 72.]
        dx: 0.3
        dy: 0.3
        time: ['1996', '1996']
  renewable:
    onwind:
      cutout: europe-1996-sarah3-era5
    offwind-ac:
      cutout: europe-1996-sarah3-era5
    offwind-dc:
      cutout: europe-1996-sarah3-era5
    offwind-float:
      cutout: europe-1996-sarah3-era5
    solar:
      cutout: europe-1996-sarah3-era5
    solar-hsat:
      cutout: europe-1996-sarah3-era5
    hydro:
      cutout: europe-1996-sarah3-era5

cy1996-nomds:
  sector:
    stores: []
    storage_units: ["li-ion battery", "vanadium", "lair", "pair"]
  snapshots:
    start: "1996-01-01"
    end: "1997-01-01"
  atlite:
    default_cutout: europe-1996-sarah3-era5
    cutouts:
      europe-1996-sarah3-era5:
        module: [sarah, era5] # in priority order
        x: [-12., 42.]
        y: [33., 72.]
        dx: 0.3
        dy: 0.3
        time: ['1996', '1996']
  renewable:
    onwind:
      cutout: europe-1996-sarah3-era5
    offwind-ac:
      cutout: europe-1996-sarah3-era5
    offwind-dc:
      cutout: europe-1996-sarah3-era5
    offwind-float:
      cutout: europe-1996-sarah3-era5
    solar:
      cutout: europe-1996-sarah3-era5
    solar-hsat:
      cutout: europe-1996-sarah3-era5
    hydro:
      cutout: europe-1996-sarah3-era5

nogasppde-mid-capex-mds:
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
    chp_extendable_DE: false
  costs:
    investment:
      iron-air battery: 18477  # in EUR/MWh (2020) from 20,000 EUR/MWh (2024)
  electricity:
    powerplants_filter: DateOut >= 2024 and not Fueltype.isin(['Nuclear', 'Hard Coal', 'Lignite']) and not (Fueltype == 'Natural Gas' and Country == 'DE')
    custom_powerplants: DateIn <= 2024 and DateOut >= 2024 and not (Fueltype == 'Natural Gas' and Country == 'DE')

nogasppde-low-capex-mds:
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
    chp_extendable_DE: false
  costs:
    investment:
      iron-air battery: 14089  # in EUR/MWh (2020) from 15,250 EUR/MWh (2024)
  electricity:
    powerplants_filter: DateOut >= 2024 and not Fueltype.isin(['Nuclear', 'Hard Coal', 'Lignite']) and not (Fueltype == 'Natural Gas' and Country == 'DE')
    custom_powerplants: DateIn <= 2024 and DateOut >= 2024 and not (Fueltype == 'Natural Gas' and Country == 'DE')

nogasppde-nomds:
  sector:
    stores: []
    storage_units: ["li-ion battery", "vanadium", "lair", "pair"]
    chp_extendable_DE: false
  electricity:
    powerplants_filter: DateOut >= 2024 and not Fueltype.isin(['Nuclear', 'Hard Coal', 'Lignite']) and not (Fueltype == 'Natural Gas' and Country == 'DE')
    custom_powerplants: DateIn <= 2024 and DateOut >= 2024 and not (Fueltype == 'Natural Gas' and Country == 'DE')

delayed-nep-mid-capex-mds:
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
  costs:
    investment:
      iron-air battery: 18477  # in EUR/MWh (2020) from 20,000 EUR/MWh (2024)
  scenario:
    ll:
      - v1.06  # limit to confirmed projects from NEP links to model a delay in the planning/permitting
  transmission_projects:
    enable: true
    include:
      tyndp2020: false
      nep: true
      manual: false
    skip:
      - upgraded_lines
      - upgraded_links
    status:
      #      - under_construction
      #      - in_permitting
      - confirmed
      #- planned_not_yet_permitted
      #- under_consideration
    new_link_capacity: zero #keep or zero

delayed-nep-low-capex-mds:
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
  costs:
    investment:
      iron-air battery: 14089  # in EUR/MWh (2020) from 15,250 EUR/MWh (2024)
  scenario:
    ll:
      - v1.06  # limit to confirmed projects from NEP links to model a delay in the planning/permitting
  transmission_projects:
    enable: true
    include:
      tyndp2020: false
      nep: true
      manual: false
    skip:
      - upgraded_lines
      - upgraded_links
    status:
      #      - under_construction
      #      - in_permitting
      - confirmed
      #- planned_not_yet_permitted
      #- under_consideration
    new_link_capacity: zero #keep or zero

delayed-nep-nomds:
  sector:
    stores: []
    storage_units: ["li-ion battery", "vanadium", "lair", "pair"]
  scenario:
    ll:
      - v1.06  # limit to confirmed projects from NEP links to model a delay in the planning/permitting
  transmission_projects:
    enable: true
    include:
      tyndp2020: false
      nep: true
      manual: false
    skip:
      - upgraded_lines
      - upgraded_links
    status:
      #      - under_construction
      #      - in_permitting
      - confirmed
      #- planned_not_yet_permitted
      #- under_consideration
    new_link_capacity: zero #keep or zero

gasprice-peak-mid-capex-mds:
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
  costs:
    investment:
      iron-air battery: 18477  # in EUR/MWh (2020) from 20,000 EUR/MWh (2024)
    fuel:
      OCGT: 38.84 # https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:52022SC0230 (Annex)
      CCGT: 38.84
      gas: 38.84

gasprice-peak-low-capex-mds:
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
  costs:
    investment:
      iron-air battery: 14089  # in EUR/MWh (2020) from 15,250 EUR/MWh (2024)
    fuel:
      OCGT: 38.84 # https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:52022SC0230 (Annex)
      CCGT: 38.84
      gas: 38.84

gasprice-peak-nomds:
  sector:
    stores: []
    storage_units: ["li-ion battery", "vanadium", "lair", "pair"]
  costs:
    fuel:
      OCGT: 38.84 # https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:52022SC0230 (Annex)
      CCGT: 38.84
      gas: 38.84
