# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

main-no-mds:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: []
    storage_units: ["li-ion battery", "vanadium", "lair", "pair"]

main-mds:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]

main-mds-h2-storage:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: []
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery", "H2"]

main-mds-no-methanation:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
    methanation: false

main-mds-vanilla:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "iron-air battery"]

main-mds-vanilla-dac-limit-ev35:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    land_transport_electric_share:
      2035: 0.35 # default assumptions
    land_transport_ice_share:
      2035: 0.65
    stores: ["H2"]
    storage_units: ["li-ion battery", "iron-air battery"]
    dac: true
    dac_limit:
        enable: true
        2035: 20  # limit in MtCO2

main-mds-vanilla-dac-limit-ev40:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    land_transport_electric_share:
      2035: 0.40 # default assumptions
    land_transport_ice_share:
      2035: 0.60
    stores: ["H2"]
    storage_units: ["li-ion battery", "iron-air battery"]
    dac: true
    dac_limit:
        enable: true
        2035: 20  # limit in MtCO2

main-mds-vanilla-dac-limit-ev45:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    land_transport_electric_share:
      2035: 0.45 # default assumptions
    land_transport_ice_share:
      2035: 0.55
    stores: ["H2"]
    storage_units: ["li-ion battery", "iron-air battery"]
    dac: true
    dac_limit:
        enable: true
        2035: 20  # limit in MtCO2

main-mds-vanilla-dac-limit-ev45-nuc80:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    land_transport_electric_share:
      2035: 0.45 # default assumptions
    land_transport_ice_share:
      2035: 0.55
    stores: ["H2"]
    storage_units: ["li-ion battery", "iron-air battery"]
    dac: true
    dac_limit:
        enable: true
        2035: 20  # limit in MtCO2
  conventional:
    nuclear:
      p_min_pu: 0.8

main-no-mds-vanilla:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: []
    storage_units: ["li-ion battery"]

main-mds-vanilla-no-methanation:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "iron-air battery"]
    methanation: false

main-mds-vanilla-with-grids:
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      vanadium: [10]
      lair: [12]
      pair: [24]
      H2: [168]
      iron-air battery: [100]
  sector:
    stores: ["H2"]
    storage_units: ["li-ion battery", "iron-air battery"]
    H2_network: true
    gas_network: true
    H2_retrofit: true

baseline-mds-chocolate-daclimit-ev30-dh30:
  enable:
    final_adjustment: true
  co2_budget:
    2035: 0.084 # excluding domestic transport emissions and non co2 energy emissions from scope
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      H2: [168]
      iron-air battery: [100]
  sector:
    district_heating:
      potential: 0.3
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
    land_transport_electric_share:
      2035: 0.30 # Compromise: FE input & IEA Global EV data explorer EU (STEPS scenario)
    land_transport_ice_share:
      2035: 0
    dac: true
    dac_limit:
        enable: true
        2035: 20  # limit in MtCO2
    co2_sequestration_potential:
      2035: 40
    residential_heat_dsm: true
    residential_heat_restriction_value: 0.27
    residential_heat_restriction_time: [10, 22] # 9am and 9pm
  load:
    scaling_factor: 1.26  # electricity load increase PyPSA 2013 to 2035 (https://www.agora-energiewende.de/fileadmin/Projekte/2021/2021_11_DE_KNStrom2035/2022-06-23_Praesentation_Klimaneutrales_Stromsystem_2035.pdf)

baseline-mds-chocolate-daclimit20-ev30-dh30-seq60:
  enable:
    final_adjustment: true
  co2_budget:
    2035: 0.084 # excluding domestic transport emissions and non co2 energy emissions from scope
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      H2: [168]
      iron-air battery: [100]
  sector:
    district_heating:
      potential: 0.3
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
    land_transport_electric_share:
      2035: 0.30 # Compromise: FE input & IEA Global EV data explorer EU (STEPS scenario)
    land_transport_ice_share:
      2035: 0
    dac: true
    dac_limit:
        enable: true
        2035: 20  # limit in MtCO2
    co2_sequestration_potential:
      2035: 60
    residential_heat_dsm: true
    residential_heat_restriction_value: 0.27
    residential_heat_restriction_time: [10, 22] # 9am and 9pm
  load:
    scaling_factor: 1.26  # electricity load increase PyPSA 2013 to 2035 (https://www.agora-energiewende.de/fileadmin/Projekte/2021/2021_11_DE_KNStrom2035/2022-06-23_Praesentation_Klimaneutrales_Stromsystem_2035.pdf)

baseline-mds-chocolate-daclimit12-ev30-dh30-seq37:
  enable:
    final_adjustment: true
  co2_budget:
    2035: 0.084 # excluding domestic transport emissions and non co2 energy emissions from scope
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      H2: [168]
      iron-air battery: [100]
  sector:
    district_heating:
      potential: 0.3
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
    land_transport_electric_share:
      2035: 0.30 # Compromise: FE input & IEA Global EV data explorer EU (STEPS scenario)
    land_transport_ice_share:
      2035: 0
    dac: true
    dac_limit:
        enable: true
        2035: 12.4  # limit in MtCO2
    co2_sequestration_potential:
      2035: 37.2
    residential_heat_dsm: true
    residential_heat_restriction_value: 0.27
    residential_heat_restriction_time: [10, 22] # 9am and 9pm
  load:
    scaling_factor: 1.26  # electricity load increase PyPSA 2013 to 2035 (https://www.agora-energiewende.de/fileadmin/Projekte/2021/2021_11_DE_KNStrom2035/2022-06-23_Praesentation_Klimaneutrales_Stromsystem_2035.pdf)

baseline-mds-chocolate-daclimit20-ev30-dh30-seq40-nomethanation:
  enable:
    final_adjustment: true
  co2_budget:
    2035: 0.084 # excluding domestic transport emissions and non co2 energy emissions from scope
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      H2: [168]
      iron-air battery: [100]
  sector:
    district_heating:
      potential: 0.3
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
    land_transport_electric_share:
      2035: 0.30 # Compromise: FE input & IEA Global EV data explorer EU (STEPS scenario)
    land_transport_ice_share:
      2035: 0
    dac: true
    dac_limit:
        enable: true
        2035: 20  # limit in MtCO2
    methanation: false
    co2_sequestration_potential:
      2035: 40
    residential_heat_dsm: true
    residential_heat_restriction_value: 0.27
    residential_heat_restriction_time: [10, 22] # 9am and 9pm
  load:
    scaling_factor: 1.26  # electricity load increase PyPSA 2013 to 2035 (https://www.agora-energiewende.de/fileadmin/Projekte/2021/2021_11_DE_KNStrom2035/2022-06-23_Praesentation_Klimaneutrales_Stromsystem_2035.pdf)

baseline-mds-chocolate-daclimit20-ev30-dh30-seq60-1H:
  enable:
    final_adjustment: true
  co2_budget:
    2035: 0.084 # excluding domestic transport emissions and non co2 energy emissions from scope
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      H2: [168]
      iron-air battery: [100]
  sector:
    district_heating:
      potential: 0.3
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
    land_transport_electric_share:
      2035: 0.30 # Compromise: FE input & IEA Global EV data explorer EU (STEPS scenario)
    land_transport_ice_share:
      2035: 0
    dac: true
    dac_limit:
        enable: true
        2035: 20  # limit in MtCO2
    co2_sequestration_potential:
      2035: 60
    residential_heat_dsm: true
    residential_heat_restriction_value: 0.27
    residential_heat_restriction_time: 10, 22] # 9am and 9pm
  load:
    scaling_factor: 1.26  # electricity load increase PyPSA 2013 to 2035 (https://www.agora-energiewende.de/fileadmin/Projekte/2021/2021_11_DE_KNStrom2035/2022-06-23_Praesentation_Klimaneutrales_Stromsystem_2035.pdf)
  clustering:
    temporal:
      resolution_sector: 1H

baseline-mds-strawberry-daclimit20-seq60:
  enable:
    final_adjustment: true
  co2_budget:
    2035: 0.084 # excluding domestic transport emissions and non co2 energy emissions from scope
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      H2: [168]
      iron-air battery: [100]
  sector:
    district_heating:
      potential: 0.3
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
    land_transport_electric_share:
      2035: 0.30 # Compromise: FE input & IEA Global EV data explorer EU (STEPS scenario)
    land_transport_ice_share:
      2035: 0
    dac: true
    dac_limit:
        enable: true
        2035: 20  # limit in MtCO2
    co2_sequestration_potential:
      2035: 60
    residential_heat_dsm: true
    residential_heat_restriction_value: 0.27
    residential_heat_restriction_time: [10, 22] # 9am and 9pm
  load:
    scaling_factor: 1.26  # electricity load increase PyPSA 2013 to 2035 (https://www.agora-energiewende.de/fileadmin/Projekte/2021/2021_11_DE_KNStrom2035/2022-06-23_Praesentation_Klimaneutrales_Stromsystem_2035.pdf)

baseline-mds-strawberry-daclimit12-seq37:
  enable:
    final_adjustment: true
  co2_budget:
    2035: 0.084 # excluding domestic transport emissions and non co2 energy emissions from scope
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      H2: [168]
      iron-air battery: [100]
  sector:
    district_heating:
      potential: 0.3
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
    land_transport_electric_share:
      2035: 0.30 # Compromise: FE input & IEA Global EV data explorer EU (STEPS scenario)
    land_transport_ice_share:
      2035: 0
    dac: true
    dac_limit:
        enable: true
        2035: 12.4  # limit in MtCO2
    co2_sequestration_potential:
      2035: 37.2
    residential_heat_dsm: true
    residential_heat_restriction_value: 0.27
    residential_heat_restriction_time: [10, 22] # 9am and 9pm
  load:
    scaling_factor: 1.26  # electricity load increase PyPSA 2013 to 2035 (https://www.agora-energiewende.de/fileadmin/Projekte/2021/2021_11_DE_KNStrom2035/2022-06-23_Praesentation_Klimaneutrales_Stromsystem_2035.pdf)

baseline-mds-strawberry-daclimit20-seq40-nomethanation:
  enable:
    final_adjustment: true
  co2_budget:
    2035: 0.084 # excluding domestic transport emissions and non co2 energy emissions from scope
  electricity:
    max_hours:
      li-ion battery: [1, 2, 4, 8]
      H2: [168]
      iron-air battery: [100]
  sector:
    district_heating:
      potential: 0.3
    stores: ["H2"]
    storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
    land_transport_electric_share:
      2035: 0.30 # Compromise: FE input & IEA Global EV data explorer EU (STEPS scenario)
    land_transport_ice_share:
      2035: 0
    dac: true
    dac_limit:
        enable: true
        2035: 20  # limit in MtCO2
    methanation: false
    co2_sequestration_potential:
      2035: 40
    residential_heat_dsm: true
    residential_heat_restriction_value: 0.27
    residential_heat_restriction_time: [10, 22] # 9am and 9pm
  load:
    scaling_factor: 1.26  # electricity load increase PyPSA 2013 to 2035 (https://www.agora-energiewende.de/fileadmin/Projekte/2021/2021_11_DE_KNStrom2035/2022-06-23_Praesentation_Klimaneutrales_Stromsystem_2035.pdf)